export const RECEIVES_USERS = 'RECEIVES_USERS';
export const RECEIVES_PRODUCTS = 'RECEIVES_PRODUCTS';
export const SET_AUTHEDUSER = 'SET_AUTHEDUSER';
export const LOGGED_OUT = 'LOGGED_OUT';
export const ADD_USER = 'ADD_USER';

export const TOGGLE_CART_TO_WISHLIST = 'TOGGLE_CART_TO_WISHLIST';
//

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_WISHLIST = 'REMOVE_WISHLIST';
export const TOGGLE_WISHLIST_TO_CART = 'TOGGLE_WISHLIST_TO_CART';
